FROM edoburu/pgbouncer@sha256:4c1ca296ef525f108f5d3552cc337c0c09587cf8dae7f0067fd93349e47dc1cd

COPY pgbouncer/pgbouncer.ini /etc/pgbouncer/pgbouncer.ini

ARG DB_PASSWORD_ARG
RUN echo '"postgres" "'$DB_PASSWORD_ARG'"' > /etc/pgbouncer/userlist.txt
